// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesCase.Data;

#nullable disable

namespace MyWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("RazorPagesCase.Models.SR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Age")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFQRdone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsSMEReviewed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Issue")
                        .HasColumnType("TEXT");

                    b.Property<int>("POD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SRs");
                });
#pragma warning restore 612, 618
        }
    }
}
